package com.fuchuanboy.todaylunch

import android.app.Activity
import android.os.Bundle
import android.graphics.Color
import android.view.Gravity
import android.widget.*
import java.text.SimpleDateFormat
import java.util.Calendar
import java.util.Locale
import kotlin.random.Random

class MainActivity : Activity() {
    data class Dish(val name:String,val type:String,val ingredient:String,val image:String,val protein:Int,val fiber:Int,val calcium:Int,val iron:Int,val desc:String)
    private var meal=mutableListOf<Dish>()
    private val favorites=mutableListOf<Dish>()
    private lateinit var body:LinearLayout
    private var tab=0

    private val pork=listOf("青椒","蒜薹","芹菜","木耳","洋葱","豆角","茄子","土豆","白菜","萝卜","冬瓜","莲藕","香菇","杏鲍菇","平菇","酸菜","梅菜","笋","蒜苗","韭菜","黄瓜","西葫芦","苦瓜","青豆","毛豆","豇豆","四季豆","豆芽","粉条","千张")
    private val beef=listOf("洋葱","芹菜","青椒","彩椒","土豆","番茄","西兰花","杏鲍菇","金针菇","木耳","蒜薹","萝卜","胡萝卜","芥蓝","豆芽","韭黄","酸菜","粉丝","豆腐","冬瓜","山药","莲藕","青豆","土豆片","娃娃菜","生菜","香菇","茶树菇","大葱","包菜")
    private val lamb=listOf("大葱","洋葱","孜然","香菜","萝卜","土豆","胡萝卜","白菜","芹菜","青椒","番茄","山药","冬瓜","酸菜","粉丝","金针菇","蒜薹","韭菜","香菇","白萝卜","彩椒","豆腐","包菜","莴笋","莲藕","土豆片","青蒜","辣椒","花菜","杏鲍菇")
    private val chicken=listOf("香菇","土豆","青椒","板栗","番茄","芹菜","木耳","洋葱","青豆","玉米","胡萝卜","山药","莲藕","冬瓜","茶树菇","金针菇","粉条","豆腐","毛豆","豇豆","花生","西兰花","彩椒","娃娃菜","南瓜","大葱","蒜香","柠檬","荷兰豆","蘑菇")
    private val duck=listOf("魔芋","土豆","冬瓜","萝卜","青椒","酸菜","香菇","莲藕","山药","芋头","豆腐","白菜","啤酒","海带","笋","梅干菜","毛豆","洋葱","紫苏","红椒")
    private val fish=listOf("豆腐","酸菜","番茄","葱","蒜","辣椒","剁椒","萝卜","冬瓜","紫苏","白菜","金针菇","粉丝","木耳","藕","蒜薹","青椒","香菜","芹菜","洋葱","茄子","泡椒","酸萝卜","海带","豆芽","雪菜","菌菇","老豆腐","丝瓜","芥菜")
    private val shrimp=listOf("西兰花","芦笋","黄瓜","鸡蛋","豆腐","玉米","豌豆","毛豆","丝瓜","冬瓜","韭菜","芹菜","番茄","蘑菇","腰果","青椒","荷兰豆","彩椒","蒜薹","葱","粉丝","南瓜","菠菜","芥蓝","胡萝卜")
    private val egg=listOf("番茄","韭菜","青椒","木耳","虾仁","洋葱","菠菜","黄瓜","香椿","香菇","西葫芦","蒜薹","玉米","豌豆","青豆","银鱼","豆腐","紫菜","芹菜","葱")
    private val beans=listOf("麻婆豆腐","家常豆腐","葱烧豆腐","香煎豆腐","小葱拌豆腐","香干炒芹菜","香干炒肉","腐竹木耳","腐竹烧肉","豆皮炒青椒","千张炒芹菜","千张结烧肉","豆腐泡烧白菜","毛豆烧豆腐","青豆虾仁","凉拌豆皮","香菇豆腐","白菜豆腐","酸菜豆腐","番茄豆腐")
    private val vegetables=listOf("上海青","小白菜","菠菜","油麦菜","空心菜","苋菜","生菜","菜心","芥蓝","娃娃菜","大白菜","包菜","西兰花","菜花","芦笋","芹菜","蒜薹","豇豆","四季豆","毛豆","茄子","番茄","黄瓜","丝瓜","冬瓜","苦瓜","西葫芦","土豆","莲藕","山药","胡萝卜","白萝卜","青椒","彩椒","洋葱","豆芽","韭菜","韭黄","香菇","平菇","杏鲍菇","金针菇","木耳","海带","莴笋","春笋","藕带","秋葵","南瓜","佛手瓜","瓠瓜","芥菜","菜薹","红薯叶")
    private val porkM=listOf("小炒","红烧","酱烧","蒜香","干煸","家常","鱼香","香辣","葱爆","梅菜烧")
    private val beefM=listOf("小炒","黑椒炒","洋葱炒","水煮","红烧","孜然炒","葱爆","酱烧","咖喱","番茄炖")
    private val lambM=listOf("葱爆","孜然炒","红烧","炖","小炒","香辣","酱烧","番茄炖","萝卜炖","干煸")
    private val chickenM=listOf("香菇烧","土豆烧","红烧","黄焖","宫保","辣子","咖喱","照烧","蒜香煎","葱油")
    private val duckM=listOf("红烧","啤酒焖","魔芋烧","酸菜炖","香辣","酱烧","莲藕炖","冬瓜炖")
    private val fishM=listOf("清蒸","红烧","水煮","酸菜炖","剁椒蒸","香煎","葱烧","番茄炖","豆瓣烧","紫苏烧")
    private val shrimpM=listOf("白灼","蒜蓉炒","清炒","盐水","香煎","椒盐","葱香")
    private val eggM=listOf("炒","煎","蒸","烧","滑炒","家常")
    private val vegM=listOf("清炒","蒜蓉炒","蚝油炒","炝炒","醋溜","红烧","干煸","上汤")
    private val fusion=listOf("照烧鸡腿","洋葱肥牛","咖喱鸡肉饭","黑椒牛柳","日式咖喱猪排","番茄牛腩","韩式辣鸡","照烧猪排","咖喱牛肉饭","黑椒鸡柳","蜜汁叉烧","日式肥牛饭","泰式柠檬鸡","葱油鸡饭","香辣鸡排","咖喱虾仁","黑椒牛肉粒","照烧鸡翅","韩式辣炒猪肉","日式姜烧猪肉","咖喱羊肉饭","番茄鸡肉煲","照烧鱼排","泰式酸辣虾","韩式辣牛肉","日式照烧鸭","咖喱鱼块","黑椒虾仁","番茄鸡排","照烧猪里脊")
    private val seasonal=mapOf(1 to listOf("菠菜","白菜","上海青","芥蓝","萝卜","西兰花"),2 to listOf("菠菜","菜心","上海青","芥蓝","生菜","西兰花"),3 to listOf("菠菜","菜心","油麦菜","芹菜","春笋","西兰花"),4 to listOf("油麦菜","上海青","苋菜","芦笋","莴笋","西葫芦"),5 to listOf("空心菜","苋菜","生菜","油麦菜","丝瓜","西兰花"),6 to listOf("空心菜","苋菜","油麦菜","丝瓜","豇豆","黄瓜"),7 to listOf("空心菜","苋菜","丝瓜","豇豆","毛豆","黄瓜"),8 to listOf("空心菜","苋菜","丝瓜","豇豆","毛豆","冬瓜"),9 to listOf("空心菜","油麦菜","上海青","丝瓜","西兰花","芥蓝"),10 to listOf("菠菜","上海青","白菜","芥蓝","西兰花","萝卜"),11 to listOf("菠菜","白菜","上海青","芥蓝","萝卜","西兰花"),12 to listOf("菠菜","白菜","上海青","芥蓝","萝卜","菜心"))

    override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);newMeal();shell();home()}
    private fun shell(){val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(Color.rgb(247,249,246))};body=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};val scroll=ScrollView(this).apply{addView(body)};root.addView(scroll,LinearLayout.LayoutParams(-1,0,1f));root.addView(nav(),LinearLayout.LayoutParams(-1,70));setContentView(root)}
    private fun home(){tab=0;body.removeAllViews();val box=page();text(box,"⌖ 河南省 · 郑州市  ▾",13,Color.DKGRAY,Gravity.LEFT,0,6,0,6);text(box,"今天中午吃什么？",31,Color.rgb(25,100,55),Gravity.CENTER,0,8,0,2);text(box,"营养均衡 · 时令搭配 · 科学膳食",15,Color.GRAY,Gravity.CENTER,0,0,0,12);val hero=TextView(this).apply{text="🥬       🍖\n\n🍚   🥣   🥩\n\n🍅       🥦";textSize=34f;gravity=Gravity.CENTER;setBackgroundColor(Color.rgb(238,247,229));setPadding(0,18,0,18)};box.addView(hero,LinearLayout.LayoutParams(-1,230).apply{setMargins(0,0,0,10)});val b=Button(this).apply{text="🎲  随机一桌\n生成今日四菜一汤";textSize=17f;setTextColor(Color.WHITE);setBackgroundColor(Color.rgb(55,165,91));setOnClickListener{newMeal();mealPage()}};box.addView(b,LinearLayout.LayoutParams(-1,68).apply{setMargins(0,4,0,12)});val f=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};listOf("✓\n营养均衡","🍊\n时令食材","🥩\n猪肉为主","🍚\n中式百味").forEach{f.addView(TextView(this).apply{text=it;gravity=Gravity.CENTER;textSize=12f},LinearLayout.LayoutParams(0,54,1f))};box.addView(f);card(box,"菜库规模","${libraryCount()} 道可组合菜品。中国菜海纳百川，除了传统家常菜，也包括照烧鸡腿、洋葱肥牛、咖喱鸡肉饭、黑椒牛柳等家庭常见融合口味。");card(box,"随机规则","猪肉作为主要动物蛋白；牛肉、羊肉、鸡肉、鸭肉、鱼虾轮换。每桌四菜一汤，固定包含一份当季烧青菜，并尽量搭配豆制品或蛋类。");body.addView(box)}
    private fun mealPage(){tab=0;body.removeAllViews();val box=page();val top=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL};text(top,"‹",30,Color.DKGRAY,Gravity.CENTER,0,0,8,0).setOnClickListener{home()};text(top,"今日午餐",23,Color.DKGRAY,Gravity.CENTER,0,0,0,0).layoutParams=LinearLayout.LayoutParams(0,52,1f);text(top,"↻",27,Color.DKGRAY,Gravity.CENTER,8,0,0,0).setOnClickListener{newMeal();mealPage()};box.addView(top);text(box,SimpleDateFormat("M月d日  EEEE",Locale.CHINA).format(Calendar.getInstance().time)+"    时令："+seasonName(),13,Color.GRAY,Gravity.LEFT,4,0,0,8);text(box,"🍃  今日四菜一汤",21,Color.rgb(30,110,60),Gravity.CENTER,0,0,0,10);meal.forEachIndexed{i,d->dishCard(box,d,when(i){0->"猪肉主菜";1->"动物蛋白轮换";2->if(d.type=="bean"||d.type=="egg")"豆制品 / 蛋类" else "第二道荤菜";3->"当季烧青菜";else->"汤品"})};card(box,"营养搭配评分","${score()} 分 · 蛋白质、蔬菜、膳食纤维、钙、铁综合评价");val change=Button(this).apply{text="换一桌  ·  无尽随机";textSize=16f;setOnClickListener{newMeal();mealPage()}};box.addView(change,LinearLayout.LayoutParams(-1,52).apply{setMargins(0,10,0,14)});body.addView(box)}
    private fun recipes(){tab=1;body.removeAllViews();val box=page();text(box,"菜谱",25,Color.rgb(30,70,45),Gravity.CENTER,0,10,0,4);text(box,"海纳百川的中式菜库 · 3000+ 可组合菜品",14,Color.GRAY,Gravity.CENTER,0,0,0,12);card(box,"菜库统计","${libraryCount()} 道可生成菜品。不同肉类、食材、做法组合后，实际随机空间远大于页面展示的固定清单。");val cats=listOf("猪肉" to pork.size*porkM.size,"牛肉" to beef.size*beefM.size,"羊肉" to lamb.size*lambM.size,"鸡肉" to chicken.size*chickenM.size+3,"鸭肉" to duck.size*duckM.size,"鱼类" to fish.size*fishM.size,"虾类" to shrimp.size*shrimpM.size,"蛋类" to egg.size*eggM.size,"豆制品" to beans.size,"时令蔬菜" to vegetables.size*vegM.size);cats.forEach{(name,count)->val r=TextView(this).apply{text="$name\n$count 道 · 点开随机一道";textSize=16f;setTextColor(Color.DKGRAY);setPadding(18,12,18,12);setBackgroundColor(Color.WHITE);setOnClickListener{detail(sample(name))}};box.addView(r,LinearLayout.LayoutParams(-1,76).apply{setMargins(0,4,0,0)})};card(box,"融合口味","${fusion.joinToString(" · ")} 等。中式餐桌并不排斥世界风味，只要适合家庭午餐，就可以进入菜库。");body.addView(box)}
    private fun favoritesPage(){tab=2;body.removeAllViews();val box=page();text(box,"收藏",25,Color.rgb(30,70,45),Gravity.CENTER,0,10,0,12);if(favorites.isEmpty())card(box,"还没有收藏","进入菜谱详情，点击 ☆ 就能收藏。") else favorites.forEach{dishCard(box,it,"我的收藏")};body.addView(box)}
    private fun mine(){tab=3;body.removeAllViews();val box=page();text(box,"营养分析",25,Color.rgb(30,70,45),Gravity.CENTER,0,10,0,12);text(box,"${score()}\n营养均衡度",30,Color.rgb(45,145,78),Gravity.CENTER,0,8,0,12);val p=meal.sumOf{it.protein};val f=meal.sumOf{it.fiber};val c=meal.sumOf{it.calcium};val i=meal.sumOf{it.iron};listOf("蛋白质" to if(p>=14)"充足" else "良好","膳食纤维" to if(f>=9)"充足" else "良好","钙" to if(c>=6)"较好" else "一般","铁" to if(i>=7)"较好" else "一般","时令绿叶菜" to if(meal.any{it.type=="green"})"达标" else "需要增加").forEach{(a,b)->val r=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL;setPadding(14,8,14,8)};text(r,a,15,Color.DKGRAY,Gravity.LEFT,0,0,0,0).layoutParams=LinearLayout.LayoutParams(0,-2,1f);text(r,b,14,Color.rgb(55,150,80),Gravity.RIGHT,0,0,0,0);box.addView(r,48,LinearLayout.LayoutParams.MATCH_PARENT)};card(box,"搭配评价","猪肉主菜 + 动物蛋白轮换 + 豆制品/蛋类 + 当季烧青菜 + 汤品。评分用于日常午餐搭配参考，不替代个体化营养建议。");card(box,"河南时令","当前优先：${seasonal[month()]!!.joinToString("、")}。");body.addView(box)}
    private fun nav():LinearLayout{val n=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER;setBackgroundColor(Color.WHITE)};listOf("⌂\n今日午餐","▣\n菜谱","☆\n收藏","♙\n我的").forEachIndexed{i,s->n.addView(TextView(this).apply{text=s;gravity=Gravity.CENTER;textSize=12f;setTextColor(if(i==tab)Color.rgb(40,150,75) else Color.GRAY);setOnClickListener{when(i){0->home();1->recipes();2->favoritesPage();else->mine()}}},LinearLayout.LayoutParams(0,-1,1f))};return n}
    private fun newMeal(){val g=seasonal[month()]!!.random();val rt=listOf("beef","lamb","chicken","duck","fish","shrimp").random();val third=if(Random.nextInt(100)<20)special() else if(Random.nextBoolean())eggBean() else protein("chicken",chicken.random(),chickenM.random());meal=mutableListOf(protein("pork",pork.random(),porkM.random()),protein(rt,ingredientsFor(rt).random(),methodsFor(rt).random()),third,green(g),soup())}
    private fun protein(type:String,ingredient:String,method:String):Dish{val name=when{type=="beef"&&ingredient=="洋葱"->"洋葱肥牛";type=="chicken"&&method=="照烧"->"照烧鸡腿";type=="chicken"&&method=="咖喱"->"咖喱鸡肉饭";else->method+proteinName(type)+ingredient};val image=when(type){"pork"->"🍖";"beef"->"🥩";"lamb"->"🥩";"chicken"->"🍗";"duck"->"🦆";"fish"->"🐟";else->"🦐"};val desc=when(name){"洋葱肥牛"->"肥牛片配洋葱快炒，咸香微甜，特别适合配米饭。";"照烧鸡腿"->"鸡腿煎香后收照烧汁，外香里嫩。";"咖喱鸡肉饭"->"鸡肉、土豆和胡萝卜煮入咖喱汁，配米饭。";else->"$method${proteinName(type)}搭配$ingredient，家常口味，适合午餐。"};val p=if(type=="beef"||type=="lamb")5 else 4;return Dish(name,type,ingredient,image,p,2,if(ingredient.contains("豆腐"))3 else 1,if(type=="pork"||type=="beef"||type=="lamb")2 else 1,desc)}
    private fun special():Dish{val n=fusion.random();val t=when{n.contains("牛|肥牛".toRegex())->"beef";n.contains("羊")->"lamb";n.contains("鸭")->"duck";n.contains("虾")->"shrimp";n.contains("鱼")->"fish";n.contains("猪|排骨|叉烧".toRegex())->"pork";else->"chicken"};return Dish(n,t,"融合风味","🍛",5,2,2,2,"$n：家庭常见的融合口味，适合米饭，纳入中式海纳百川菜库。")}
    private fun eggBean():Dish{if(Random.nextBoolean()){val x=egg.random();return Dish("家常炒鸡蛋·$x","egg",x,"🍳",2,2,2,1,"鸡蛋与${x}搭配，快炒即可。")};val x=beans.random();return Dish(x,"bean",x,"🥣",3,2,4,2,"豆制品提供植物蛋白，家常做法简单下饭。")}
    private fun green(x:String)=Dish("${vegM.random()}${x}","green",x,"🥬",1,4,1,2,"当季${x}大火快炒，少油少盐，保持脆嫩。")
    private fun soup():Dish{val x=listOf("番茄蛋花汤","紫菜蛋花汤","冬瓜排骨汤","菌菇豆腐汤","萝卜瘦肉汤","青菜豆腐汤","冬瓜虾皮汤","丝瓜蛋汤","菠菜蛋花汤","紫菜虾皮汤","玉米排骨汤","山药排骨汤","莲藕排骨汤","海带排骨汤","冬瓜丸子汤","白菜豆腐汤","酸辣汤","三鲜汤","菌菇鸡蛋汤","丝瓜虾仁汤","番茄豆腐汤","毛豆蛋汤","鱼头豆腐汤","菌菇鸡汤","萝卜牛腩汤","酸菜鱼汤","菌菇瘦肉汤","冬瓜肉丸汤","紫菜豆腐汤","玉米鸡汤").random();return Dish(x,"soup","","🍲",1,1,if(x.contains("豆腐|紫菜|虾皮".toRegex()))3 else 1,1,"食材洗净后煮至熟透，最后少盐调味。")}
    private fun sample(cat:String):Dish=when(cat){"猪肉"->protein("pork",pork.random(),porkM.random());"牛肉"->protein("beef",beef.random(),beefM.random());"羊肉"->protein("lamb",lamb.random(),lambM.random());"鸡肉"->protein("chicken",chicken.random(),chickenM.random());"鸭肉"->protein("duck",duck.random(),duckM.random());"鱼类"->protein("fish",fish.random(),fishM.random());"虾类"->protein("shrimp",shrimp.random(),shrimpM.random());"蛋类"->eggBean();"豆制品"->eggBean();else->green(seasonal[month()]!!.random())}
    private fun detail(d:Dish){body.removeAllViews();val box=page();val top=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL};text(top,"‹",30,Color.DKGRAY,Gravity.CENTER,0,0,8,0).setOnClickListener{recipes()};text(top,d.name,22,Color.DKGRAY,Gravity.CENTER,0,0,0,0).layoutParams=LinearLayout.LayoutParams(0,52,1f);val s=TextView(this).apply{text=if(favorites.any{it.name==d.name})"★" else "☆";textSize=28f;gravity=Gravity.CENTER;setTextColor(Color.rgb(235,175,25));setOnClickListener{if(favorites.any{it.name==d.name})favorites.removeAll{it.name==d.name}else favorites.add(d);detail(d)}};top.addView(s,45,LinearLayout.LayoutParams.MATCH_PARENT);box.addView(top);text(box,"${d.image}\n${d.name}",40,Color.rgb(60,80,55),Gravity.CENTER,0,12,0,12);card(box,"这道菜",d.desc);card(box,"食材准备",ingredients(d));card(box,"怎么做",steps(d));card(box,"营养特点","蛋白质 ${d.protein} · 膳食纤维 ${d.fiber} · 钙 ${d.calcium} · 铁 ${d.iron}");card(box,"小贴士","家庭午餐建议少油少盐；肉类、蛋类、鱼虾彻底加热。");body.addView(box)}
    private fun ingredients(d:Dish)=when(d.type){"pork"->"猪肉、${d.ingredient}、葱姜蒜、生抽、食用油";"beef"->"肥牛/牛肉、${d.ingredient}、洋葱、黑胡椒、生抽";"lamb"->"羊肉、${d.ingredient}、大葱、孜然、香菜";"chicken"->"鸡腿/鸡肉、${d.ingredient}、葱姜蒜、生抽；照烧另加蜂蜜或照烧汁";"duck"->"鸭肉、${d.ingredient}、姜、葱、生抽";"fish"->"鲜鱼、${d.ingredient}、姜、葱、生抽";"shrimp"->"鲜虾、${d.ingredient}、葱姜、少量食用油";"egg"->"鸡蛋、${d.ingredient}、葱花、食用油";"bean"->"豆制品、${d.ingredient}、葱姜蒜、生抽";"green"->"${d.ingredient}、蒜、少量食用油、盐";"soup"->"对应汤品主料、葱姜、少量盐";else->"主料、时令蔬菜、葱姜蒜、基础调味料"}
    private fun steps(d:Dish)=when{d.name=="照烧鸡腿"->"1. 鸡腿擦干，划几刀。\n2. 少油煎至两面金黄。\n3. 加生抽、少量蜂蜜和清水。\n4. 小火收汁，鸡肉熟透。\n5. 切块装盘。";d.name=="洋葱肥牛"->"1. 洋葱切丝。\n2. 肥牛快速焯至变色。\n3. 少油炒香洋葱。\n4. 放肥牛、生抽、黑胡椒快速翻匀。\n5. 出锅配米饭。";d.name=="咖喱鸡肉饭"->"1. 鸡肉、土豆、胡萝卜切块。\n2. 鸡肉煎至变色。\n3. 加水煮至食材熟。\n4. 加咖喱块小火收浓。\n5. 配米饭。";d.type=="green"->"1. 洗净切段。\n2. 蒜末爆香。\n3. 大火快炒。\n4. 少盐调味，断生即出锅。";d.type=="fish"->"1. 鱼处理洗净。\n2. 姜葱去腥。\n3. 按菜名清蒸、红烧或水煮。\n4. 鱼肉完全熟透。";d.type=="shrimp"->"1. 虾去虾线洗净。\n2. 姜葱去腥。\n3. 大火炒至变色并熟透。\n4. 少盐调味。";d.type=="soup"->"1. 食材洗净切块。\n2. 入锅加水。\n3. 小火煮熟。\n4. 撇浮沫，少盐调味。";else->"1. 肉类切片或切块，少量生抽腌制。\n2. 热锅少油，先将肉类炒至变色。\n3. 加${d.ingredient}及葱姜蒜翻炒或焖炖。\n4. 根据菜名调味。\n5. 确保肉类完全熟透后出锅。"}
    private fun score():Int{var s=80;s+=if(meal.count{it.type in listOf("pork","beef","lamb","chicken","duck","fish","shrimp")}>=2)6 else 2;s+=if(meal.any{it.type=="green"})5 else 0;s+=if(meal.any{it.type=="bean"||it.type=="egg"})4 else 1;s+=if(meal.sumOf{it.fiber}>=9)3 else 1;return s.coerceIn(80,98)}
    private fun libraryCount()=pork.size*porkM.size+beef.size*beefM.size+lamb.size*lambM.size+chicken.size*chickenM.size+duck.size*duckM.size+fish.size*fishM.size+shrimp.size*shrimpM.size+egg.size*eggM.size+vegetables.size*vegM.size+beans.size+30*20+30
    private fun ingredientsFor(t:String)=when(t){"beef"->beef;"lamb"->lamb;"chicken"->chicken;"duck"->duck;"fish"->fish;else->shrimp}
    private fun methodsFor(t:String)=when(t){"beef"->beefM;"lamb"->lambM;"chicken"->chickenM;"duck"->duckM;"fish"->fishM;else->shrimpM}
    private fun proteinName(t:String)=when(t){"pork"->"猪肉";"beef"->"牛肉";"lamb"->"羊肉";"chicken"->"鸡肉";"duck"->"鸭肉";"fish"->"鱼";else->"虾"}
    private fun seasonName()=when(month()){3,4,5->"春季";6,7,8->"夏季";9,10,11->"秋季";else->"冬季"}
    private fun month()=Calendar.getInstance().get(Calendar.MONTH)+1
    private fun page()=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(16,8,16,18)}
    private fun text(p:LinearLayout,s:String,size:Number,color:Int,gravity:Int,l:Int,t:Int,r:Int,b:Int):TextView{return TextView(this).apply{this.text=s;textSize=size.toFloat();setTextColor(color);this.gravity=gravity;setPadding(l,t,r,b);p.addView(this)}}
    private fun card(p:LinearLayout,title:String,content:String){val c=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(14,12,14,12);setBackgroundColor(Color.WHITE)};text(c,title,16f,Color.rgb(35,90,50),Gravity.LEFT,0,0,0,5);text(c,content,13f,Color.DKGRAY,Gravity.LEFT,0,0,0,0);p.addView(c,LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,6,0,0)})}
    private fun dishCard(p:LinearLayout,d:Dish,label:String){val r=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(8,8,8,8);setBackgroundColor(Color.WHITE);setOnClickListener{detail(d)}};text(r,d.image,38f,Color.DKGRAY,Gravity.CENTER,0,0,0,0);val q=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(10,0,0,0)};text(q,d.name,17f,Color.rgb(35,35,35),Gravity.LEFT,0,0,0,3);text(q,label,12f,Color.rgb(60,145,80),Gravity.LEFT,0,0,0,3);text(q,"蛋白质 ${if(d.protein>=4)"较高" else "适中"} · 点开看做法 ›",12f,Color.GRAY,Gravity.LEFT,0,0,0,0);r.addView(q,LinearLayout.LayoutParams(0,-2,1f));p.addView(r,LinearLayout.LayoutParams(-1,92).apply{setMargins(0,4,0,0)})}
}
